### PR TITLE
Fix issue updating sensitive project environment variables

### LINKED ISSUE #154: Cannot update sensitive environment variables
When you try to change the value of a sensitive environment variable, it fails.

image

The provider should do a replacement if the underlying API doesn't allow updating.

We have to be able to update the variable, how else do you rotate secrets?

Workaround is to manually delete the secret in the Vercel dashboard before planning/applying.

### PR DESCRIPTION
**Pull request by dglsparsons**
Closes #154

### CODE REVIEW

File: vercel/resource_project_environment_variable_test.go [hunk 1]
```diff
@@ -214,7 +214,7 @@ resource "vercel_project_environment_variable" "example_git_branch" {
 resource "vercel_project_environment_variable" "example_sensitive" {
 	project_id = vercel_project.example.id
 	%[3]s
-	key        = "foo_sensitive_updated"
+	key        = "foo_sensitive"
```
Comment (dglsparsons) [inline vercel/resource_project_environment_variable_test.go:217]: The test was faulty - updating the key forced a replacement, so it wasn't really testing that the other fields can be updated.

File: client/environment_variable_update.go [hunk 2]
```diff
@@ -10,7 +10,6 @@ import (
 // UpdateEnvironmentVariableRequest defines the information that needs to be passed to Vercel in order to
 // update an environment variable.
 type UpdateEnvironmentVariableRequest struct {
-	Key       string   `json:"key"`
```
Comment (dglsparsons) [inline client/environment_variable_update.go:13]: Key is required-replace, so should not be present in the update request.

**Review by craigandrews — DISMISSED** [review]

**Review by craigandrews — APPROVED** [review]
